### PR TITLE
Tauri-plugin-store-api improvements

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
This PR adds the following
- only bundles webview-dist files
- create minified and non-minified builds
- upgrade ts configuration
- add temp `type-fest` dependency until latest commits of @tauri-apps/api is published

### CODE REVIEW

**Review by lucasfernog — APPROVED** [review]
Nice :)

**Comment by lucasfernog** [comment]
Is it by design that the MJS build is non-minified and the CJS one is always minified?

**Comment by JonasKruckenberg** [comment]
The minified one is also esm, look at the last line: `export{W as default};`

**Comment by JonasKruckenberg** [comment]
The minified file is meant to be used stand-alone in situations where people don't want to use a bundler, and the non-minified where people use bundlers (and can benefit from generated sourcemaps)

**Comment by lucasfernog** [comment]
Makes sense, want it to get merged now?

**Comment by JonasKruckenberg** [comment]
That'd be cool yeah!

**Pull request merged**
