### PR TITLE
Changing types

### LINKED ISSUE #16: [store] Mistypes in TS part of the lib
I believe there are two mistypes:

1. [here](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/webview-src/index.ts#L117) should go `T[]` for function return value
2. [here](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/webview-src/index.ts#L189) should go `T | null` for `value` argument

### LINKED ISSUE #92: `.values()` return `string[]` instead of `T[]`
I believe [this line](https://github.com/tauri-apps/tauri-plugin-store/blob/dev/webview-src/index.ts#L117) contains a typing error.

### PR DESCRIPTION
**Pull request by dkzlv**
Fixes tauri-apps/plugins-workspace#16

### CODE REVIEW

**Comment by dkzlv** [comment]
@JonasKruckenberg Also I wasn't sure if I'm supposed to rebuild the lib manually, but I didn't find a GA setup for this, so I did it anyway. Can drop if needed.

**Comment by JonasKruckenberg** [comment]
Yeah just build the package and check it into git. We want people to be able to use plugins directly from git, without having to go through npm if they don't one.

**Comment by dkzlv** [comment]
Already did it.

**Comment by JonasKruckenberg** [comment]
Oh sorry, one last thing: can you add a changefile summarizing what you did?

**Comment by dkzlv** [comment]
@JonasKruckenberg All done!

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Looks all good to me except the fact that you haven't signed your commits. [Here's a guide on how to do so](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

Just sign the commmits and force push to this branch so everything is signed

**Comment by FabianLars** [comment]
Closing due to inactivity in favor of #133

**Pull request closed without merging**
